### ISSUE TITLE
passer les tests en python

### ISSUE THREAD

**Issue by titibs29** [titibs29/API_AA_SOA#1]
les tests sont disponibles en lua, et doivent être disponibles en python
- [x] écrire les tests en lua
- [ ] réecrire les tests lua en python
- [ ] créer de nouveaux tests (optionel)
